### PR TITLE
Add support for NAT traversal techniques

### PR DESCRIPTION
**Pull request by oleiba**
Extending the PR #1051, by allowing to specify specific protocol (TCP/UDP) for a NAT traversal technique.
This is important in particular for the case of registering a DHT port as UDP.

I here add the original author's comments for clarity:

> Here is an implementation of NAT traversal as discussed in #195 using https://github.com/indutny/node-nat-upnp and https://github.com/TooTallNate/node-nat-pmp.
> 
> I have also ecountered https://github.com/level451/pmp that claims to make both UPnP ad NAT-PMP but I don't have tested it.
> 
> This feature is implemented in a new module for node env only and provided by a single instance shared by the webtorrent clients because NAT-PMP needs to open a specific port to work.
> 
> I checked the UPnP part with my router by it does not support NAT-PMP protocol.
> 
> The mappings are sent both with UPnP and NAT-PMP whe available and refreshed every 30 min.
> 
> Reviews are welcome!

### CODE REVIEW

**Comment by mayeaux** [comment]
I was told this functionality is working, can anyone confirm?

**Comment by RangerMauve** [comment]
This'd be pretty nice to have. Would any of the collaborators have the bandwidth to push through an updated PR?

**Comment by RangerMauve** [comment]
Just pulled this PR and fixed conflicts [in my branch](https://github.com/RangerMauve/webtorrent/tree/nat-traversal)

It seems to have helped as people can connect to me now. Sadly, it looks like running two processes is broken because I get the following error:

```
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5350
    at dgram.js:339:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Client instance at:
    at Client.onerror (/home/mauve/programming/bt-sync/node_modules/nat-pmp/index.js:363:10)
    at Socket.<anonymous> (/home/mauve/programming/bt-sync/node_modules/nat-pmp/index.js:371:32)
    at Socket.emit (events.js:310:20)
    at dgram.js:341:14
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 5350
}
```

Gonna look into this, might be an error in the nat-pmp module.

**Comment by RangerMauve** [comment]
Yeah, adding `addressReuse:true` to `dgram.createSocket` fixed it. I'll submit a patch there. 🤷

**Comment by RangerMauve** [comment]
Submitted a PR which fixes node-pnp in multi-process scenarios. https://github.com/TooTallNate/node-nat-pmp/pull/14

Also updated my branch of webtorrent to incorporate this patch and the one that was previously being used.

Down to submit a new PR or somehow update this one. 😁

**Comment by RangerMauve** [comment]
Still interested in this. 😅

**Comment by resession** [comment]
this would be great to have

**Comment by Rucadi** [comment]
This seems a small PR and could be super useful for my needs. Is there any chance it will be merged?

**Pull request closed without merging**
