### PR TITLE
feat: support adding paused torrents.

### PR DESCRIPTION
**Pull request by nkavian**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] New feature

**What changes did you make? (Give an overview)**

The use case I'd like to solve is that a torrent file and it's contents are stored in disk, I'd like to add the torrent to the `client` and be able to benefit from the programmatic interface provided by `client`, `torrent`, and `file`; without being connected to peers.

Another example, if I `pause` a torrent and restart my application, I'd like to maintain that state across restarts.

Adding a torrent to the client and then pausing it is not an adequate workaround.

**Which issue (if any) does this pull request address?**

N/A

**Is there anything you'd like reviewers to focus on?**

I'm new to your code, I'm unaware if I'm changing everything that's necessary. I wanted to be able to send a PR and not just create an issue / feature request.

### CODE REVIEW

**Comment by nkavian** [comment]
Tests pass but something called airtap failed.

**Review by DiegoRBaquero — APPROVED** [review]

**Comment by DiegoRBaquero** [comment]
Do you mind rebasing to re-retrigger CI?

**Comment by nkavian** [comment]
@DiegoRBaquero the change you made was incorrect. you should have sent your own PR and allow people to comment. I would have pointed out that

A) you didn't consistently change it within the same method. You updated lines 214/215 but missed 223 and 226 in the same method.

B) the whole file uses the syntax I used, whereas now, your two lines are different, and you've associated my PR to this mistake.

**Comment by DiegoRBaquero** [comment]
It’s not a mistake, just different syntax. Will switch everything to arrow functions

**Comment by DiegoRBaquero** [comment]
See https://github.com/webtorrent/webtorrent/pull/2134

**Comment by nkavian** [comment]
I know it's a different syntax.

**Pull request merged**
