### PR TITLE
feat: use storage (FSA+IDB) instead of memory in browser

### PR DESCRIPTION
**Pull request by ThaUnknown**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Added an option to use drive storage instead of memory in browser.

Replaced memory chunk store with hybrid chunk store which will ***try*** to figure out how much space the user has on their drive, use all of it - 16MB, then fallback to memory [should this be blobs instead of memory?] for the rest, this increases the capacity on firefox and safari by 2^31 or 2.14GB, and on chrome by as much as the user has space.

Additionally on *most* chromium versions the user can specify a rootDir, which allows the user to specify a custom target download folder, which replicates the folder and file structure in the same way as node does. 

Just like node, if the browser crashes the files won't be removed, this is something the developer should handle.

**FSA specific:**

Because of the limitations of the FSA API, you cant write and save from the same file at once, [this is meant to improve](https://bugs.chromium.org/p/chromium/issues/detail?id=1323922) but there's no ETA, and [in-place read/writes are only possible in web workers](https://web.dev/file-system-access/#accessing-files-optimized-for-performance-from-the-origin-private-file-system). To work around this the FSA chunk store works in 2 modes:
- [OPFS](https://web.dev/file-system-access/#accessing-the-origin-private-file-system) mode: if no custom directory is defined the built in default storage location is used, where each chunk has it's own file, and each write opens and closes a file.
- custom directory mode: files are written to the custom directory, but individual chunks are also stored in OPFS, if a chunk exist in OPFS it's read from there, otherwise it's read from the respective files from the custom directories, this means x2 data usage, however the excess data is cleared on store close. If the browser closes too fast, and it doesn't manage to remove the store in time [ex: multi-gigabyte torrent], on the next load of the page, the excess data will be removed.

The stores are ones made by wormhole, just the FSA one is expanded to allow for extra functionality.

**Which issue (if any) does this pull request address?**
- https://github.com/orgs/webtorrent/projects/1#card-60702730
- https://github.com/webtorrent/webtorrent/issues/86
- https://github.com/webtorrent/webtorrent/issues/2389

**Is there anything you'd like reviewers to focus on?**
the new package, 
if the store is trying to do too many things at once, 
the increasing amt of store opts and how to possibly reduce this?,

### CODE REVIEW

**Comment by ThaUnknown** [comment]
@DiegoRBaquero I've removed the github dependencies, and pulled latest, you can test the functionality of this over at https://haven.pages.dev/torrent-client/public

**Comment by DiegoRBaquero** [comment]
If hybrid-chunk-store is ESM, webtorrent can't yet support it

**Comment by ThaUnknown** [comment]
> If hybrid-chunk-store is ESM, webtorrent can't yet support it

yes, but that can easily be changed, I could compile hybrid to 2 files, one module and one normal, focus on its code pls

**Comment by ThaUnknown** [comment]
forgot this went to v2 and kinda borked it, fixed merge conflict and updated hcs version

**Comment by ThaUnknown** [comment]
@DiegoRBaquero I've updated the package, also made it pass all these tests: https://github.com/ThaUnknown/hybrid-chunk-store/blob/master/test.js which are probably more strict than any of the tests used by the stores that we currently use, this is as good to merge as it's probably gonna get

**Review by DiegoRBaquero — APPROVED** [review]

**Pull request merged**
