### PR TITLE
Add global down/up speed limit

### PR DESCRIPTION
**Pull request by JohnRey9**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Add functional for control download and upload speed

**Is there anything you'd like reviewers to focus on?**
This is update for #1040

### CODE REVIEW

**Comment by willstott101** [comment]
Could you re-base onto #1804 and see if the test pass now?

**Comment by vankasteelj** [comment]
Works "almost" fine from my testing (merging the PR on the current master): download&upload speeds are limited, although Task Manager (Windows) sees wierd speeds, I wonder if behind the curtains it doesnt do "max speed -> wait -> max speed -> wait" for it to have a "global average" of set limits but in bursts. Does that make sense?

**Comment by vankasteelj** [comment]
Seeing how old is this PR and the non-response from OP, here's the doc update: 

```js
{
  maxConns: Number,        // Max number of connections per torrent (default=55)
  nodeId: String|Buffer,   // DHT protocol node ID (default=randomly generated)
  peerId: String|Buffer,   // Wire protocol peer ID (default=randomly generated)
  tracker: Boolean|Object, // Enable trackers (default=true), or options object for Tracker
  dht: Boolean|Object,     // Enable DHT (default=true), or options object for DHT
  webSeeds: Boolean,        // Enable BEP19 web seeds (default=true)
  downloadLimit: Number,     // Download speed limit in bytes - e.g. (200*1024) is 200kB or 1.6mbps
  uploadLimit: Number,    // Upload speed limit in bytes 
}
```

**Comment by vankasteelj** [comment]
Note that tests work fine locally when using `npm run test-node` and `npm run test-browser-local`

**Comment by craigharman** [comment]
Thanks for the update. I've created a PR for the docs if you can please approve @vankasteelj 

I tried the tests locally and `npm run test-node` is still failing on the client seed test:

```
# client.seed: torrent file (Buffer)
not ok 73 Error: premature close
  ---
    operator: fail
```

**Comment by vankasteelj** [comment]
I think you're mistaken me for op

**Comment by craigharman** [comment]
> I think you're mistaken me for op

@vankasteelj I merged in the docs to your fork so you can bring them into this PR

**Comment by voidpls** [comment]
A low `uploadLimit` seems to severely affect download speeds too:

```
uploadLimit          Avg Download (mB/s)
none                 43.5
1e6 bytes (1mB)      46.2
1e5 bytes (100kB)    38.5
1e4 bytes (10kB)     7.8
1e3 bytes (1kB)      0.919
```

Tested with [a Ubuntu ISO](https://releases.ubuntu.com/19.10/ubuntu-19.10-desktop-amd64.iso.torrent), and max connections at 150, on NodeJS. Can anyone else reproduce these results? It seems as if an `uploadLimit` of <100kB/s starts to heavily hamper download performance too.

**Comment by craigharman** [comment]
Suggest proceeding with https://github.com/webtorrent/webtorrent/pull/1852#pullrequestreview-410744169

**Comment by vankasteelj** [comment]
well that's a mean bot, we all here waiting for the merge

**Comment by alxhotel** [comment]
Closed by #2062

**Pull request closed without merging**
