### PR TITLE
Date based speedometer

### PR DESCRIPTION
**Pull request by Bruce-Hopkins**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

I replaced the Speedometer module with a custom one. This method has higher accuracy.  

**Which issue (if any) does this pull request address?**

#2226 

**Is there anything you'd like reviewers to focus on?**

No.

### CODE REVIEW

**Comment by Bruce-Hopkins** [comment]
This solution should be more accurate.

**Comment by ThaUnknown** [comment]
squash this pls?

**Comment by Bruce-Hopkins** [comment]
Squash the commits you mean?

**Comment by Bruce-Hopkins** [comment]
I squashed the commits. It should be good now.

**Review by DiegoRBaquero — DISMISSED** [review]

**Comment by DiegoRBaquero** [comment]
@alxhotel

**Comment by ThaUnknown** [comment]
this seems very slow

**Comment by Bruce-Hopkins** [comment]
@ThaUnknown in what way? Any suggestions on performance improvements?

**Comment by jimmywarting** [comment]
why use Date objects instead of using Date.now() that has a smaller footprint?

**Comment by alxhotel** [comment]
This implementation doesn't seem to work as expected. I'll take a stab at this

**Comment by Bruce-Hopkins** [comment]
Sure! Let me know if you need any assistance.

**Comment by Bruce-Hopkins** [comment]
@alxhotel Thanks. Let me know if you need any assistance.

**Comment by Bruce-Hopkins** [comment]
> why use Date objects instead of using Date.now() that has a smaller footprint?

I can make the change but @alxhotel is about to make changes too.

**Pull request closed without merging**
