### PR TITLE
feat: Built-in-webrtc

### PR DESCRIPTION
**Pull request by ThaUnknown**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
webrtc is now built in, this deprecates webtorrent-hybrid
**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by SilentBot1 — APPROVED** [review]
This worked as expected on all local testing, both to https://instant.webtorrent.dev and between two NodeJS WebTorrent peers via WebRTC. This looks good to me!

**Comment by QuixThe2nd** [comment]
Hi, I believe this breaks `WebTorrent.WEBRTC_SUPPORT`, as I'm on an ARM Macbook which I believe doesn't support WebTorrent, but WebTorrent.WEBRTC_SUPPORT returns as true.

**Comment by ThaUnknown** [comment]
verify it, because an "I believe" doesn't cut it, there's no reason for it to not support webrtc

**Comment by QuixThe2nd** [comment]
I can't remember where it was being used, but I remember `node-webrtc` was a dependency of WebTorrent. I can't seem to find any mentions of it now, so I'm not sure where I saw this. But node-webrtc doesn't support ARM Mac's and I can't get WebRTC connections using WebTorrent on my ARM Mac.

**Comment by ThaUnknown** [comment]
this doesn't use node-webrtc

**Comment by SilentBot1** [comment]
> Hi, I believe this breaks `WebTorrent.WEBRTC_SUPPORT`, as I'm on an ARM Macbook which I believe doesn't support WebTorrent, but WebTorrent.WEBRTC_SUPPORT returns as true.

This works as expected on ARM, the [new library](https://github.com/murat-dogan/node-datachannel) being used for WebRTC supports ARM devices. `WebTorrent.WEBRTC_SUPPORT` returning true was the goal of this PR, and deprecates the need for webtorrent-hybrid for NodeJS WebRTC connectivity.

```bash
root@arm:~/webtorrent# dpkg --print-architecture
arm64
root@arm:~/webtorrent# node
Welcome to Node.js v18.17.1.
Type ".help" for more information.
> const { default: WebTorrent } = await import("webtorrent"); const client = new WebTorrent({utp: false});
(node:90473) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:90473) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
WebTorrent: uTP not supported Error: Cannot find module 'utp-native'
[...]
undefined
> const torrent = client.add("magnet:?xt=urn:btih:4c52086259fb7b77bbccc4b4b44f88759c6a9ef7&dn=100MB.bin&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.webtorrent.dev&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337")
undefined
> Object.values(client.torrents[0]._peers).filter((p)=>p.type=='webrtc').length
1
> client.torrents[0].progress
0.1734375
```

**Pull request merged**
