### PR TITLE
Added an api method to add with timeout #2691

### PR DESCRIPTION
**Pull request by uriva**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

1. added support for timeout in the api
2. avoid throw exceptions on innocuous actions

### CODE REVIEW

**Comment by ThaUnknown** [comment]
this can be done externally by a developer by listening to the `ready` event, this pr also does bad stuff like version locking random commits and changing styling where it shouldnt, no.

**Comment by uriva** [comment]
What is "the ready event"? I don't see anything in the docs about this, so how would one go about using this?

**Comment by uriva** [comment]
Regarding the other things, I think they can be fixed if  you want to cooperate.

**Comment by uriva** [comment]
Found the ready event
Thanks

**Pull request closed without merging**
