### PR TITLE
fix: ensure uTP peer address is IPv4

### PR DESCRIPTION
**Pull request by hicom150**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Check peer address to ensure it is a valid IPv4 when using uTP protocol.

**Which issue (if any) does this pull request address?**
It should fix https://github.com/webtorrent/webtorrent/issues/2114

**Is there anything you'd like reviewers to focus on?**
I've added an internal `_isIPv4` method, just in case we want to replace its implementation with something different than https://github.com/sindresorhus/is-ip

### CODE REVIEW

**Comment by ThaUnknown** [comment]
why not use the same detection as utp-native?
https://github.com/mafintosh/utp-native/blob/master/index.js#L9

**Comment by DiegoRBaquero** [comment]
I agree, no need for the extra dep

**Comment by hicom150** [comment]
You are right about reusing https://github.com/mafintosh/utp-native code, but given that https://github.com/mafintosh/utp-native/blob/master/index.js#L9 nor https://github.com/mafintosh/utp-native/blob/master/index.js#L274 are exposed, I've fixed that by just copying the regex 😅

If in the future https://github.com/mafintosh/utp-native exposes this methods, we can easily refactor to use them 😉

**Comment by ThaUnknown** [comment]
> You are right about reusing https://github.com/mafintosh/utp-native code, but given that https://github.com/mafintosh/utp-native/blob/master/index.js#L9 nor https://github.com/mafintosh/utp-native/blob/master/index.js#L274 are exposed, I've fixed that by just copying the regex 😅
> 
> If in the future https://github.com/mafintosh/utp-native exposes this methods, we can easily refactor to use them 😉

hopefully in the future they support ipv6 instead :p

**Comment by IdanAdar** [comment]
@DiegoRBaquero Anything else needed before approving?

**Review by DiegoRBaquero — APPROVED** [review]

**Comment by DiegoRBaquero** [comment]
My bad, I was on vacation

**Pull request merged**
