### PR TITLE
Mark webseeds interested at the start, ensuring they download anything

### PR DESCRIPTION
**Pull request by ianmcorvidae**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
I've made it so there is a call to `wire.interested()` for webseed peers since it was discovered on the issue linked below that the `wire.uninterested()` further up in the file was preventing webseeds from working correctly.

I tested this manually with webseeds using a similar bit of code to the one in the issue below.

**Which issue (if any) does this pull request address?**
#1671 
possibly others

**Is there anything you'd like reviewers to focus on?**
I'd like to be sure of the correctness of this, particularly if I might have affected anything other than webseeds.

### CODE REVIEW

**Comment by DiegoRBaquero** [comment]
Could you come up with a test scenario so that this fixes and makes that test passing?

**Comment by TemaSM** [comment]
Tested, webseeds now works just fine. Thanks for fix @ianmcorvidae 👍

**Comment by hicom150** [comment]
I've been reviewing this PR and I found out that this issue seems already fixed in https://github.com/webtorrent/webtorrent/commit/a07188f87a4acb7f8b2338c3d41da1b57cb9878c and released in [v0.108.4](https://github.com/webtorrent/webtorrent/releases/tag/v0.108.4) 😅

It would be nice if @ianmcorvidae you could recheck if the issue has been solved, so we can decide if we need to merge or close this PR ;)

**Comment by ianmcorvidae** [comment]
@hicom150 I haven't looked at this in ages (obviously, I guess!) but that looks like it _should_ fix this and is a better solution than mine. To be honest, I don't even remember what I was using before to test this, so if others are having webseeds work correctly, I'm content with the released code.

**Pull request closed without merging**
