### PR TITLE
allow for progress on write

### PR DESCRIPTION
**Pull request by ftreesmilo**
I use this to show progress when dropping large files into my site to create a torrent...
This lets me show the progress of the torrent as the file is moved from File handles into the store.

### CODE REVIEW

**Comment by alxhotel** [comment]
Yep, as you've said, this seems like a nice feature for large files.

To merge this PR, I think we need a couple of things:
- Some tests
- Some documentation of the new feature

In addition, I would even consider changing the callback into an event. And be called like `on('write', () => console.log('writing to store'))`.

Also accessing a private attribute (`_blockstream`) is usually not recommended. An alternative would be to add a new "transform", in the `pump` call, between `readable` and `writable`.

**Comment by ftreesmilo** [comment]
will look into it

**Comment by ftreesmilo** [comment]
google's native fs apis have been giving me a headache...    i finally got to something I'm happy with, and I'll come back to this soon and clean things up.  I'd really like to get rid of my diffs

**Comment by ftreesmilo** [comment]
fyi i changed this to happen in my store...   it ended up being much easier, as adding the torrent with files and relying on the internal stream readers to copy them was killing performance.  It was much faster to pipe the streams in the store using the native fs.

**Comment by ftreesmilo** [comment]
please review this as well

**Pull request closed without merging**
