### PR TITLE
calculate file downloaded correctly

### PR DESCRIPTION
**Pull request by jimmywarting**
I notice `file.download` is calculated wrong.

Using the Sintel torrent as an example...
https://instant.io/#08ada5a7a6183aae1e09d831df6748d566095a10
(this can be tested in the console)

It has 6 srt files and 1 small piece of the mp4 file in the first piece
after the first piece is downloaded you can see that the first files are complete but the `progress` and `downloaded` are incorrect

```js
const file = client.get('08ada5a7a6183aae1e09d831df6748d566095a10').files[0]
console.log(file.done) // true
console.log(file.progress) // 39.58777239709443 <- incorrect b/c of download
console.log(file.downloaded) // 65399 <- this file fits inside one chunk and it's too big
console.log(file.length) // 1652
```

### CODE REVIEW

**Comment by DiegoRBaquero** [comment]
Could you maybe add a test where it fails with current code and works with your PR?

**Comment by jimmywarting** [comment]
Maybe, haven't dived in to webtorrent much

**Comment by jimmywarting** [comment]
Could you guide me in the direction of where to add the test?

**Comment by jimmywarting** [comment]
Done

**Comment by DiegoRBaquero** [comment]
I'm glad you could figure the tests out

**Comment by jimmywarting** [comment]
Thanks, i have never tried tape before, and i didn't know i needed to look into webtorrent-fixtures but I am good at reverse engineering :)

**Pull request merged**
