### PR TITLE
Allows customization of webseed http requests through an options call…

### PR DESCRIPTION
**Pull request by guanzo**
…back function.

This pull request allows users to modify the http options passed to `simple-get`, such as adding headers, query parameters, etc. `torrentOpts` now accepts a `getWebseedOpts` callback function, similar to `getAnnounceOpts`.

Relevant issues: 
https://github.com/webtorrent/webtorrent/issues/1507
https://github.com/webtorrent/webtorrent/issues/1530

### CODE REVIEW

**Comment by gruns** [comment]
:+1:

**Comment by jimmywarting** [comment]
Is this something that we would want to have if we changed to using fetch instead of simple-get?
Is there anyone interested in using fetch instead?

**Comment by guanzo** [comment]
> Is this something that we would want to have if we changed to using fetch instead of simple-get?

Sure why not. Regardless of which API handles http requests, I think allowing custom http options is important.

**Comment by DiegoRBaquero** [comment]
Where is the issue where fetch was discussed?

**Comment by jimmywarting** [comment]
Think there is none
But I brought it up in #1507

**Comment by Fenny** [comment]
Any updates?

**Comment by feross** [comment]
The spirit of this PR is good, but I think it would be nicer if this option supported configuring the HTTP request options for all the places where we send HTTP requests, not just Web Seeds. Is there any interest to send a PR that does this?

**Pull request closed without merging**
