### PR TITLE
feat: esm

### PR DESCRIPTION
**Pull request by ThaUnknown**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

ESM
tests pass \o/

additionally changed from jsdelivr to esm.sh, which is faster, ESM based and has better polyfills than what we provide

### CODE REVIEW

**Review by DiegoRBaquero — APPROVED** [review]
Nice, loving esmify

**Comment by ThaUnknown** [comment]
> Nice, loving esmify

honestly I hate browserify, and my next PR is gonna be dropping it for `esbuild` just so we can have custom polyfills

**Comment by jimaek** [comment]
jsDelivr also supports ESM https://cdn.jsdelivr.net/npm/webtorrent/+esm but at the same time you also get download stats, multi-CDN and other production functionality.

**Comment by ThaUnknown** [comment]
> jsDelivr also supports ESM https://cdn.jsdelivr.net/npm/webtorrent/+esm but at the same time you also get download stats, multi-CDN and other production functionality.

doesn't polyfill node

**Comment by MartinKolarik** [comment]
It does polyfill most of the APIs (the modules that can be reasonably polyfilled) but fails on `crypto` in this case. That said, the esm.sh link doesn't work either, if you actually try to run it:

```
import('https://esm.sh/webtorrent')
> Promise {<pending>}
> GET https://esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=dgram&importer=bittorrent-lsd net::ERR_ABORTED 500
> Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://esm.sh/webtorrent
```

**Comment by ThaUnknown** [comment]
> It does polyfill most of the APIs (the modules that can be reasonably polyfilled) but fails on `crypto` in this case. That said, the esm.sh link doesn't work either, if you actually try to run it:
> 
> ```
> import('https://esm.sh/webtorrent')
> > Promise {<pending>}
> > GET https://esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=dgram&importer=bittorrent-lsd net::ERR_ABORTED 500
> > Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://esm.sh/webtorrent
> ```

read: none?

also unfortunate, importing webtorrent via esm.sh worked a week back

**Comment by MartinKolarik** [comment]
> read: none?

Most, see https://github.com/FredKSchott/rollup-plugin-polyfill-node#nodejs-builtin-support-table

esm.sh seems to have more or less the same issue, not being able to handle `dgram` module, based on the error message

**Pull request merged**
