### PR TITLE
Much better timeouts for webseeds

### PR DESCRIPTION
**Pull request by jhiesey**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Currently, there is the standard 30 second timeout to complete one or more HTTP requests to get a piece from a webseed. Depending on the piece size, this may cause incorrect timeouts.

Instead, this PR moves the timeouts into `lib/webconn.js` and applies them as a socket timeout (interval between packets/data events), NOT a timeout for the entire request. This timeout is set to 60 seconds in this PR.

If an HTTP request fails, the webseed will cancel its requests using the `lt_donthave` extension, and then re-advertise them after a delay (currently 10 seconds) using a `have` message. This allows retries to work without completely hammering webseeds.

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by jhiesey** [comment]
To work properly in the browser, this needs an updated version of `stream-http` from this PR: https://github.com/jhiesey/stream-http/pull/121

That should be merged shortly.

**Comment by feross** [comment]
This completely fixes the issue where a web seed may hang and the torrent will never complete because webtorrent becomes uninterested in the web seed peer!

**Comment by feross** [comment]
0.117.0

**Comment by jhiesey** [comment]
`stream-http` with fixed timeout support is `v3.2.0`

**Pull request merged**
