### PR TITLE
TorrentParts

### PR DESCRIPTION
**Pull request by leoherzog**
Adds [Torrent.Parts](https://torrent.parts/) to list of projects

https://github.com/leoherzog/TorrentParts

**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Added project to list in FAQ

### CODE REVIEW

**Comment by alxhotel** [comment]
Nice tool, @leoherzog!

You need to add the URL of the website in markdown. Just like the rest of links.

**Comment by leoherzog** [comment]
Whoops. Sorry! I hadn't ever seen that list-the-URL-separately format of Markdown before :smile:

**Review by feross — APPROVED** [review]

**Comment by feross** [comment]
Looks like a useful utility.

**Comment by leoherzog** [comment]
Hey thanks!

**Comment by leoherzog** [comment]
How often is this FAQ markdown file pulled into [webtorrent.io's FAQ section](https://webtorrent.io/faq)?

**Comment by leoherzog** [comment]
@feross bump

**Pull request merged**
