### PR TITLE
Add uTP support 

### PR DESCRIPTION
**Pull request by pldubouilh**
Work in progress implementation of uTP (issue #68). It uses [utp-native](https://www.npmjs.com/package/utp-native).

Also seems to greatly help seeding - after running it for an hour on a public distro torrent, it seems to seed much more than with plain TCP BT :ok_hand:

### CODE REVIEW

**Comment by pldubouilh** [comment]
Thanks - now I think it's good to be reviewed.

Just wondering about that appveyor test issue though, might be related to mafintosh/utp-native#20 but I'm not too sure, the test kind of fails in a cryptic manner

**Comment by G-Ray** [comment]
Utp support would be great! Any update on this @DiegoRBaquero @feross ?

**Comment by pldubouilh** [comment]
Happy to resolve the conflict if utp is still of interest, otherwise I'll just close the PR.

**Comment by DiegoRBaquero** [comment]
I like this one. @feross ?

**Comment by DiegoRBaquero** [comment]
Could you update so we can move this forward?

**Comment by pldubouilh** [comment]
closing for #1486

**Pull request closed without merging**
