### PR TITLE
Feature/163 global download upload limit

### PR DESCRIPTION
**Pull request by chtrinh**
throttleDownload() and throttleUpload() helper methods for rate adjustments

#163

### CODE REVIEW

**Comment by BenmasterTM** [comment]
HI, I try this changes in the webtorrent client in the webtorrent-desktop client, and when I try to set the upload/download limit for Web Torrent, this changes dont work, the only way I found to slowdown the upload files from the webtorrent client in webtorrent-desktop is changing the webtorrent/node_modules/bittorrent-protocol/index.js changing the Wire.prototype.piece function, and encapsulating the code into a timeout:

`    var self = this;
    
    (function(self, index, offset, buffer) {
    setTimeout(function() {

    self._debug('piece index=%d offset=%d', index, offset)
    self.uploaded += buffer.length
    self.uploadSpeed(buffer.length)
    self.emit('upload', buffer.length)
    self._message(7, [index, offset], buffer)
    
    }, 800)    
    })(self, index, offset, buffer)
`
altering the timeout time change the upload speed to the web seeds, but cause many messages "start backpressure" from the simple-peer module

**Comment by chtrinh** [comment]
How did you set upload/download limits for webtorrent-desktop client? 
it should be something like this: 
```
var torrent = new WebTorrent({downloadLimit: 10240, uploadLimit: 10240}); // (downstream/upsttream) bandwidth to 10 KB/s
```
This PR relies on https://www.npmjs.com/package/stream-throttle to throttle your bandwidth.

**Comment by BenmasterTM** [comment]
Yes I try that:

```let client = window.client = new WebTorrent({downloadLimit: 10240, uploadLimit: 10240})```

but the clients connected to the webtorrent client get 100% of my internet connection, i think is because im talking always about WebRTC clients (I dont test with regular uTPC clients, but in the code I see self.type === 'tcpOutgoing' and i think the web clients go for another point)

**Comment by chtrinh** [comment]
My initial use case was for TCP not WebRTC. IIRC, I encountered an edge case where you couldn't always set throttle pipes. You don't know what "tcpIncoming" are going to be use for. 
https://github.com/chtrinh/webtorrent/blob/462a1916fc1736fa9ede2ce0240e1500efad51de/lib/peer.js#L32-L39

I would try something like so:
```js
 if ((self.type === 'tcpOutgoing') || (self.type === 'webSeed')) {
    self.setThrottlePipes()
 } else {
    conn.pipe(wire).pipe(conn)
  }
```

**Comment by BenmasterTM** [comment]
The correct value in Web Peers is self.type === 'webrtc', but works correctly, thanks!

**Comment by BenmasterTM** [comment]
Hi, I found an error in specific case: If you change the upload or download speed while torrents are downloading/uploading, and change the speed limit (with the helper function or directly in webtorrent.uploadSpeed / webtorrent.downloadSpeed, the webtorrent crash:

Error: Uncaught, unspecified "error" event. (Requested tokens 2984254 exceeds bucket size 1049600)
    at Throttle.emit (events.js:163)
    at Throttle.onerror (D:\Escritorio\electro\node_modules\webtorrent\node_modules\readable-stream\lib\_stream_readable.js:562)
    at emitOne (events.js:96)
    at Throttle.emit (events.js:188)
    at onwriteError (_stream_writable.js:344)
    at onwrite (_stream_writable.js:362)
    at afterTransform (_stream_transform.js:79)
    at TransformState.afterTransform (_stream_transform.js:54)
    at D:\Escritorio\electro\node_modules\webtorrent\node_modules\stream-throttle\src\throttle.js:34
    at _combinedTickCallback (internal/process/next_tick.js:67)
    at process._tickCallback (internal/process/next_tick.js:98)

**Comment by rigelk** [comment]
@chtrinh do you still plan on finishing this ?

**Comment by quicoto** [comment]
Any updates on this? 🙏

**Comment by TwoAbove** [comment]
@BenmasterTM unfortunately, no news on that, but I can confirm that this fork works

**Comment by craigharman** [comment]
Any chance that someone is going to look at this again? @chtrinh seems like is a few formatting issues and deletion of .min.js file away?

**Comment by ultimate-tester** [comment]
Subscribed. This pull request should be accepted. On my server the current implementation will actually at times max out on bandwidth dropping other non-torrent connections. Therefore a limit would be really appropriate.

**Comment by ultimate-tester** [comment]
Even better, I've just opened another pull request #1852 to deal with the outdated situation of this pull request. 

The essential code is 100% identical to the pull request of @chtrinh, I've merely adjusted it to fit with the ECMAScript version used in webtorrent. It will merge succesfully with the current version in master branch.

**Comment by feross** [comment]
Superceded by #1852

**Pull request closed without merging**
