### PR TITLE
Add support for NAT traversal techniques

### PR DESCRIPTION
**Pull request by yciabaud**
Here is an implementation of NAT traversal as discussed in #195 using https://github.com/indutny/node-nat-upnp and https://github.com/TooTallNate/node-nat-pmp.

I have also ecountered https://github.com/level451/pmp that claims to make both UPnP ad NAT-PMP but I don't have tested it.

This feature is implemented in a new module for node env only and provided by a single instance shared by the webtorrent clients because NAT-PMP needs to open a specific port to work.

I checked the UPnP part with my router by it does not support NAT-PMP protocol.

The mappings are sent both with UPnP and NAT-PMP whe available and refreshed every 30 min.

Reviews are welcome!

### CODE REVIEW

**Comment by yciabaud** [comment]
Looks like TooTallNate/node-nat-pmp#13 prevents Travis from running the tests

**Comment by yciabaud** [comment]
Using my patch TooTallNate/node-nat-pmp#13 does the trick, we should wait for it to be merged but I have no feedback ATM.

**Comment by heroboy** [comment]
What protocol port you used to map? As I know dht uses UDP. `self._natTraversal.portMapping` seems mapping TCP port default.

**Comment by oleiba** [comment]
That sounds interesting!
What's left for it to be merged?

**Pull request closed without merging**
